### ISSUE TITLE
npm run dist facing issue

### ISSUE THREAD

**Issue by ketanvekaria** [oikonomopo/electron-deep-linking-mac-win#21]
@Ketans-MacBook-Pro custom % **npm run dist**

> electron-deeplinking-macos-win32@0.0.1 dist /Applications/XAMPP/xamppfiles/htdocs/custom
> build

Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.40.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=5.0.1 appOutDir=dist/mac
  • default Electron icon is used reason=application icon is not set
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                  0 identities found
                                             
                                               Valid identities only
                                                  0 valid identities found
  • building        target=macOS zip arch=x64 file=dist/electron-deeplinking-macos-win32-0.0.1-mac.zip
  • building        target=DMG arch=x64 file=dist/electron-deeplinking-macos-win32-0.0.1.dmg
  • building embedded block map file=dist/electron-deeplinking-macos-win32-0.0.1-mac.zip
**Error: Exit code: 2.** Command failed: /usr/bin/perl /private/var/folders/f_/yhbfz7pn3c1bzrcw_g1r25j40000gn/T/t-wMifIL/1-dmgProperties.pl
Can't locate Mac/Memory.pm in @INC (you may need to install the Mac::Memory module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /private/var/folders/f_/yhbfz7pn3c1bzrcw_g1r25j40000gn/T/t-wMifIL/1-dmgProperties.pl line 4.
BEGIN failed--compilation aborted at /private/var/folders/f_/yhbfz7pn3c1bzrcw_g1r25j40000gn/T/t-wMifIL/1-dmgProperties.pl line 4.

Can't locate Mac/Memory.pm in @INC (you may need to install the Mac::Memory module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /private/var/folders/f_/yhbfz7pn3c1bzrcw_g1r25j40000gn/T/t-wMifIL/1-dmgProperties.pl line 4.
BEGIN failed--compilation aborted at /private/var/folders/f_/yhbfz7pn3c1bzrcw_g1r25j40000gn/T/t-wMifIL/1-dmgProperties.pl line 4.

    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
From previous event:
    at _applyProperties (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/out/dmgUtil.js:179:27)
    at applyProperties (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/out/dmgUtil.js:166:27)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/src/dmg.ts:305:9
From previous event:
    at _customizeDmg (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/out/dmg.js:455:24)
    at customizeDmg (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/out/dmg.js:399:24)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/src/dmg.ts:48:54
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/src/dmgUtil.ts:37:31
From previous event:
    at _attachAndExecute (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/out/dmgUtil.js:120:28)
    at attachAndExecute (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/out/dmgUtil.js:97:28)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/src/dmg.ts:48:16
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/macPackager.ts:90:26
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/macPackager.ts:90:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/macPackager.ts:80:95)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:178:5)
From previous event:
    at Packager.doBuild (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (fs.js:165:23)
From previous event:
    at Packager._build (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/electron-builder/src/builder.ts:228:10)
    at /Applications/XAMPP/xamppfiles/htdocs/custom/node_modules/electron-builder/src/cli/cli.ts:46:19

**Comment by oikonomopo** [comment]
Try again with latest release v1.0 or latest master branch. I've got ages to run it.
